# Default initial positions for yumi's ros2_control fake system

initial_positions:
  gripper_l_joint: 0.025
  gripper_r_joint: 0.025
  yumi_joint_1_l: 0
  yumi_joint_1_r: 0
  yumi_joint_2_l: -2.2689
  yumi_joint_2_r: -2.2689
  yumi_joint_3_l: 0.5235
  yumi_joint_3_r: 0.5235
  yumi_joint_4_l: 0
  yumi_joint_4_r: 0
  yumi_joint_5_l: 0.5235
  yumi_joint_5_r: 0.5235
  yumi_joint_6_l: 0
  yumi_joint_6_r: 0
  yumi_joint_7_l: 2.3562
  yumi_joint_7_r: -2.3562
